cookie:
  expiry_days: 30
  key: chatbot_admin_session
  name: chatbot_admin
credentials:
  usernames:
    admin:
      email: admin@ums.ac.id
      name: Administrator
      password: $2b$12$X88LVbOhKGSng77QIN5Gf.vswgGdmYKcc8L7PNbTFT8FCAeJ/aWPm
preauthorized:
  emails:
  - admin@ums.ac.id
