[client]
showErrorDetails = true

[runner]
magicEnabled = true
fastReruns = true

[server]
headless = true
runOnSave = false
port = 8501
enableCORS = false
enableXsrfProtection = true

[ui]
hideTopBar = false

[browser]
gatherUsageStats = false


